### ISSUE TITLE
Form of Publication

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#10]
From Habtom:
"Under Publication Information:
- Form of publication: instead of book, there appears “Form of Publication: Book”. Kindly remove “form of publication”, 

- Please add here: 
Editor"

**Comment by Mergpijp** [comment]
Okay this is easy to fix so you want 'Form of Publication: Book' to be changed to 'Editor: Book'?

**Comment by Elisagig** [comment]
No, 

We want "Form of Publication: Book"to be changed to "Book" 
And we want also to add an extra entry saying "Editor" because some books are "edited by" and not only authored.

**Comment by Mergpijp** [comment]
So if I understand correctly the drop down select2 text needs to be changed for example 'Form of Publication: Book' to only the name: 'Book'.
And add a new field Editor below the previous field.

**Comment by Elisagig** [comment]
Yes. Editor should come under author. So in case it is an old book from long ago authored by St. Nichoalus for example and then the book was reprinted and edited by John Wayne for example, we have the option to add that.
