### ISSUE TITLE
Change "Original Title" name

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#103]
Dear colleagues,

The team feels the tab heading "original title" is a bit confusing. change that to "Title" please.

Thanks.

**Comment by Woseseltops** [comment]
Hey @Elisagig , this one is a duplicate of #102 , right?

**Comment by Mergpijp** [comment]
This I dont understand. The tab heading in create page is Titles and the first entry is named: Title original. Do you want to change that?

**Comment by Woseseltops** [comment]
I think that's what Elise means, yes. 

Just to be sure, @Elisagig. The current situation is that we have for every publication a 'Title original', 'Title subtitle transcription' and 'Title translation'. Renaming 'Title original' to 'Title' would indeed make clearer that this is default/main title, but maybe less clear what is the relation to the other two. You could also consider something like 'Original title' or 'Title in the original language'.

**Comment by Elisagig** [comment]
This issue came bcs some publications have titles in 2 languages and the question came bcs we do not always know or can judge one language as original and one as not original. So the team requested we just call it "Title"

**Comment by Mergpijp** [comment]
Yes this is done had to rewrite alot and will be deployed later.

**Comment by Elisagig** [comment]
Looking forward. I close it for now then
