### ISSUE TITLE
Admin rights for @elisagig

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#104]
See the question by @elisagig to create an account for Christopher Sheklian in your email... but perhaps it would be more efficient to give her the option to do it herself? 

If @Mergpijp agrees and it's not clear for @elisagig how it works, we can use this issue to explain.

**Comment by Mergpijp** [comment]
Okay, made elise admin. It is very simple: One goes to : [globalorthodoxy.csl.ru.nl/admin](globalorthodoxy.csl.ru.nl/admin) . 
The CSS is not loaded so it is a bit ugly but you can see Site Administration in bold.  One can see Users Add Change. Press Add. After that just follow the instructions. Just generate a strong password from : [https://passwordsgenerator.net/](https://passwordsgenerator.net/). And done!

**Comment by Elisagig** [comment]
Tried. Getting 404 error. Don't know what the problem is

**Comment by Mergpijp** [comment]
hmm github is not linking correctly. Ill make a new url: [URL](https://globalorthodoxy.cls.ru.nl/admin/) it is working now?

**Comment by Elisagig** [comment]
Ok now I see why. I was using Microsoft Edge not Chrome. It opens on Chrome but requests a password

**Comment by Mergpijp** [comment]
Hmm I made you staff did u login with your credentials?

**Comment by Mergpijp** [comment]
By the way Christopher has an account
