### ISSUE TITLE
Search function not working today

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#106]
Is it a bug? Team informed me they can't search today

**Comment by Woseseltops** [comment]
@Mergpijp thinks this is related to a connection to Google Translate that we make that is shut down by Google. He will make it so the automatic translation functionality is turned off temporarily.

**Comment by Mergpijp** [comment]
Yes my suspicion was correct do you need it  deployed now? I am continuing to the next high prio deploy later.

**Comment by Elisagig** [comment]
Ok then we wait until the next high pro deploy. In case my colleagues ask: around when should that be ready? Thanks

**Comment by Mergpijp** [comment]
This was already done friday because the other high prio issue was easy. Hope it works

**Comment by Elisagig** [comment]
Will check again but Heleen said yesterday that it is working but in a weird way

**Comment by Elisagig** [comment]
Hi guys my colleagues said they receive weird Java script there. There is a new Search related problem today. I do not know if I should add it as a new issue. When you go to files and search for the file or photo you are getting a wrong photo attached or not always finding the photo.

**Comment by Mergpijp** [comment]
So tested this on my local database and to clarify if you search on image title it will make a search query so you can get other results. Do you want it to exactly match the uploadedfile and return that publication?

**Comment by Elisagig** [comment]
We basically want to be able to add the name or parts of the name and be able to retrieve it. My colleagues sent me this document. I summarized parts of it to you already 
![Uploading Screenshot_20210202-102148_Word.jpg…]()

**Comment by Mergpijp** [comment]
There appears some trouble linking in your message. Please try again.

**Comment by Elisagig** [comment]
![Screenshot_20210202-102148_Word](https://user-images.githubusercontent.com/61408472/107116982-5caa6580-6877-11eb-8e48-ffbee6a7201a.jpg)

**Comment by Mergpijp** [comment]
Okay so there are still two things that can be improved: 

- First a general edit on the title page should also be able to edit existing authors/translators and also other related fields.  
- Second there should be a thrashbin for uploadedfiles to be able to restore.

**Comment by Mergpijp** [comment]
For the first point it is already possible. Just search or unlink a author and press the little pencil for the author you want to edit.
The second point requires some work on my part.

**Comment by Mergpijp** [comment]
So made this and deployed this. Kindly check. Note that deleting uploadedfiles will not delete the picture (this was always like this). This way one can restore uploadedfiles completely.

**Comment by Elisagig** [comment]
Thanks. Informed my colleagues. Looks good for me but waiting their final confirmation

**Comment by Elisagig** [comment]
Answer from my colleague Matija:
"TGanks Elise, it works for me. But there's another problem with authors now; I see that in several publications I uploaded there's no author visible and when I edit it and add the author, it's still not showing after I save the changes".

**Comment by Mergpijp** [comment]
Yes recognizable error. This is due to form validation failing on edit. Fixed this by copying the form validation from create. Deployed now.
