### ISSUE TITLE
Title summary in interface

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#110]
My colleagues informed me yesterday that the titles now look summarized with three dots (...) at the interface even though there is place for them in the boxes. Since there is space in the box they want a bigger part of the title to show. I will share a photo to explain what I mean

**Comment by Elisagig** [comment]
![Screenshot_20210205-094644_Zoom](https://user-images.githubusercontent.com/61408472/107117049-bf036600-6877-11eb-812b-8660c13510d6.jpg)

**Comment by Mergpijp** [comment]
This can be fixed quickly the fixed value of 35 characters is to little. Ill make it a 100 characters see how it looks.

**Comment by Elisagig** [comment]
Thanks :)
