### ISSUE TITLE
Make image contents a free text field

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#113]
We want to do some smart stuff with text later to make relations, but for now the more 'keyword' like approach does not seem to match how users want to use it.

**Comment by Woseseltops** [comment]
Make sure the old data is converted to free text, so no data is lost.

**Comment by Woseseltops** [comment]
Make sure to make an extra backup before you deploy this one.

**Comment by Elisagig** [comment]
Matija discovered that the problem is happening when there are commas. Commas create separate entities (this can be fixed through ‘navigate’), but it can be created by adding a semicolon at the end of the sentence/text.

**Comment by Mergpijp** [comment]
Okay but this is no issue? I think I converted all image content correctly?

**Comment by Elisagig** [comment]
Yes will check. I copied this issue from another one and closed it in order not to duplicate. Sorry I was on vacation the past days and don't know yet if this has been resolved
