### ISSUE TITLE
Uploading a second file: clear the data from the first one

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#114]

**Comment by Mergpijp** [comment]
This does also apply for author and translator modals.

**Comment by Woseseltops** [comment]
This works when closing with the cross (and possibly also save), but not by clicking besides the modal.

**Comment by Mergpijp** [comment]
I used an event to capture modal dismiss.

**Comment by Elisagig** [comment]
Still an issue mentioned on 25 Feb
"Uploading images – when you upload a new image, while you are still on the create page, the data from the previous image are still showing so you have to clear everything and then add the next image"

**Comment by Mergpijp** [comment]
Yes this is fixed but not yet deployed. Can deploy now if you wish
