### ISSUE TITLE
"The results could not be loaded" for FileCategory when adding a new UploadedFile

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#115]
@Mergpijp mentioned this might be related to Redis.

**Comment by Woseseltops** [comment]
Also create a unit test for this!

**Comment by Mergpijp** [comment]
I have no idea how to write a unit test for functionality deep in the application.

**Comment by Woseseltops** [comment]
@Mergpijp is stuck here. Once he figures it out, this should also be on the hotfix branch and deployed directly.

**Comment by Elisagig** [comment]
Ok I assume this is the same as what the colleagues just mention "File category and image content work properly ‘the other way around’ (through ‘navigate’)". Succes met oplossen!

**Comment by Mergpijp** [comment]
This has been fixed note that image contents is now a charfield.

**Comment by Elisagig** [comment]
Thanks
