### ISSUE TITLE
Export button for search results

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#117]
Let's make it a tab separated list, but call it CSV, so Excel will open it automatically.

**Comment by Mergpijp** [comment]
The problem with excel is that it does not read the arabic text. Notepad++ does give the correct output seperated by tabs.
Did not do anything with manytomany fields.

**Comment by Mergpijp** [comment]
So to force excel to open CSV in UTF-8 I followed this guide: [https://stackoverflow.com/a/6488070/11153552](https://stackoverflow.com/a/6488070/11153552)

**Comment by Woseseltops** [comment]
Next step: come up with some kind of message to inform users how to open the CSV in Excel.

**Comment by Mergpijp** [comment]
This is done
