### ISSUE TITLE
Add search field filters

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#118]
Example search question: in how many publications images of mary are being used?

**Comment by Woseseltops** [comment]
Another, different usecase by Habtom: if I enter Tewahdo in Latin, I get longer list than when I use "Tewahdo" in Ge'ez...  how can we refine this so that we get all the Tewahdo books, the Armenian books in one go?"

**Comment by Elisagig** [comment]
Also to be added to better search functionality the following:

More refined queries in the comments section (search functionality for keywords to be found from the comments section)

**Comment by Woseseltops** [comment]
The default is that all individual search terms are searched for in all fields. We want to be able to limit the fields that are searched. It could look like this:

![image](https://user-images.githubusercontent.com/1909317/114167846-c1de0e00-992f-11eb-8dfa-7e4f54644fb6.png)

If no button is activated, you just get the default behavior, otherwise you only search in the activated fields. 

Notes: 
* Not sure when this extra menu should pop up... maybe when you hover the search field or the search button?
* Some fields like ImageContents, are 3 (!) steps away from the actual publications you are searching (publication > uploaded file > image content), which might be technically complicated.

**Comment by Woseseltops** [comment]
Steps to build this:
* First UI that appears on hover
* Send extra input field (checkboxes) along with the post request
* When processing the post request, make the filters more specific

**Comment by Mergpijp** [comment]
hmm dont know what description fields is now set at content description..

**Comment by Woseseltops** [comment]
Emmanuel showed me this works. Perhaps later: make sure that selected fields are persistent, similar to how the search term is persistent.

**Comment by Elisagig** [comment]
Can you please explain what you mean? Thanks

**Comment by Woseseltops** [comment]
Moved the persistency to #154
