### ISSUE TITLE
Separate popups not closing after the action is done is confusing

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#119]
While we are working with modals more and more, there are still some places in the application where separate popups are used, like when creating a new city. When the newly created city is saved, however, the popup does not disappear automatically, which some users find confusing.

Possible solutions
* Close the popup with Javascript (might not be possible for all browsers, though)
* Switch to modals
* Redirect to a new page, saying 'you can close this popup now' .

**Comment by Mergpijp** [comment]
I think the best way is to switch to modals. The other solutions will need to know that the popup came  from the create/edit view which is cumbersome.
