### ISSUE TITLE
Tabs/titles moving

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#12]
From Habtom
"We have different tabs: Title, Author, Publishing Information, Affiliation, Language, Content, Collection Info, Files… 
If I open, for example, Publishing Information, then I don’t see the title of the book/the item". Is it possible to make it visible/fixed? It would be helpful

**Comment by Mergpijp** [comment]
Okay, this could be a tricky one. So you want to see the titles when going to publishing information? Am I right? There is no easy way to fix this I am afraid but will be looking for a fix.

**Comment by Elisagig** [comment]
I think what Habtom meant was to see the titles while filling info in general. I can ask him again today to be sure and get back to you

**Comment by Elisagig** [comment]
Please let us ignore this point until I talk to Habtom to make sure I get it right
