### ISSUE TITLE
New issue: Publication Country

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#123]
Publication country - Cannot erase country on the create page (if I already chose a country from the list but then decided to leave it empty – e.g. it wasn’t clear in the book where it was published so I decided to leave it empty for now)

**Comment by Mergpijp** [comment]
Yes required was not set. Now it is allowed to clear publication country

**Comment by Woseseltops** [comment]
Added this to sprint 1, will be live end of next week.
