### ISSUE TITLE
Continue in create page

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#127]
Got this from some colleagues: 
"If I want to add Affiliated Church, then I press +; after I add the affiliated Church, I press Submit; instead of going back to Create Page I am moved to: “Add New Church”... Why not return to the Create Page? If I want to add a new church, I can always press again + I know, I can always press X on the top right ... ;  but I want to continue in the Create Page without doing that..."

**Comment by Mergpijp** [comment]
All the create + have been changed into modals so this should be solved.

**Comment by Elisagig** [comment]
Thanks. They informed me today. Will the changes be deployed soon?
