### ISSUE TITLE
 Save issue again

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#13]
I remember Emanuelle that you told me there are 3 options. Either to have the trash that comes again (option 2) or to be able to save each time right? Not possible to combine both?
From Habtom:
"When you enter anything and push on Sumbit then you go back to the “Add new Publications” window. Is it possible that what you entered be saved without pushing the Submit button?"

**Comment by Mergpijp** [comment]
Yes this is possible will be working on options 1 and 2 and release them as soon as i can.

**Comment by Elisagig** [comment]
Great. Looking forward

**Comment by Mergpijp** [comment]
So for option 1 I did some research and found that one can save sessions with a pend button. I don't know if this is enough because saving sessions on closing the web application seems hard. The good thing is that there is a lot of documentation on it. Would this be acceptable?

**Comment by Elisagig** [comment]
I do not understand what you mean. This is not very clear to me. Could you explain? Do not want to make it too complicated for you.

**Comment by Mergpijp** [comment]
Well saving your progress while editing or making new publications. For this there needs to be a separate button 'Pend'. Because exiting the website will cause to lose your data. Will discuss this with wessel.

**Comment by Elisagig** [comment]
Prima. If it is complicated then we can keep it as it is. Matija told me it is not difficult to keep doing submit each time

**Comment by Mergpijp** [comment]
It is okay the implementation is possible but will keep the priority lower for now.

**Comment by Elisagig** [comment]
Prima. Ok let us focus on the other things and get back later to this

**Comment by Mergpijp** [comment]
So for now option 2 is implemented. Now users cannot really delete a publication. 
It will appear in the thrash bin and one can only restore publications.
