### ISSUE TITLE
Add Search for UploadedFiles

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#132]
How to search within the subitems of ‘Navigate’ (especially within ‘uploaded files’)? (using the search field brings one back to the main page for the results – not to the ‘uploaded files’ that contain the search term)

**Comment by Woseseltops** [comment]
@Elisagig do you think 'Add search for all other objects as well (not only publication)' would be a good name for this issue?

**Comment by Elisagig** [comment]
Yes I agree

**Comment by Elisagig** [comment]
Is the issue clear at your end?

**Comment by Elisagig** [comment]
Again, colleagues contacted me today saying that the search option within the 'Author' and 'Files' columns sometimes works, sometimes it doesn't.

**Comment by Mergpijp** [comment]
hmm I understand the problem but I have no idea how to implement this.

**Comment by Woseseltops** [comment]
Let's start with UploadedFiles, as it seems to be mostly needed there.  I guess it makes most sense that the search bar is aware of what kind of page you are looking at, and responds differently when you are looking at the list view, detail view, create/edit view of uploaded files.

**Comment by Woseseltops** [comment]
Doesn't fit in sprint 2 anymore, moving to the next one.

**Comment by Mergpijp** [comment]
Okay this is done I need to find a way to hide menu of #118  when in uploadedfile-show.

**Comment by Woseseltops** [comment]
Looking good. Two ideas:
* Rename the button to 'Search publications' or 'Search uploaded files', to make clear to the users which search functionality they are about to use.
* Remove the field filter popup for uploaded files.
