### ISSUE TITLE
Increase number of limited words comments

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#14]
From Habtom
"The number of signs for the comment section are as many as for twitter: is it possible to have more space in the comment section?"

**Comment by Mergpijp** [comment]
Yes this is possible currently it sits at 200 characters, how many do you want?

**Comment by Elisagig** [comment]
Shall we say 400? I do not know. I need to ask the guys. Let us try 400 and see.

**Comment by Mergpijp** [comment]
Okay, easy to fix will be done soon.
