### ISSUE TITLE
Add extra column for search results: 'Search terms appear in'

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#141]
When displaying search results, for example for the search 'mary', add an extra column showing in which fields the search term appears. Something like:

| | | | Search terms appear in |
|-|-|-|-|
| | | | author name, keywords |
| | | | keywords, decription |

etc

Importantly, this column should also appear in the export (but only when exporting search results).

**Comment by Woseseltops** [comment]
In case the database query approach by @vanlummelhuizen does not work, you could also just iterate over all hits, and then over all fields, and just check if the query string is inside the value.

**Comment by Woseseltops** [comment]
This takes more time than expected, let's move this out of the current sprint.

**Comment by Woseseltops** [comment]
Current approach: add it as a field to the model.

Suggested approach: create a separate list, hand this list to the Django template. Template checks if there is a query. If so, add extra that uses the separate list.

**Comment by Mergpijp** [comment]
Yes your approach works its now in context_data.

**Comment by Woseseltops** [comment]
Two minor improvements:
* Did not see the human friendliness during the demo (still saw underscores)
* When there were multiple images, the same field is present more than once.

Tip for the last issue: using a Python `set()` instead of a list `[]` makes duplicates impossible.

**Comment by Mergpijp** [comment]
Did not use set used pythons in variable. (This could have been easier). Made a function make_human_friendly to replace underscores with spaces.

**Comment by Woseseltops** [comment]
@Mergpijp indicates both issues are done, will be available at next deploy
