### ISSUE TITLE
The three save buttons don't do as they say

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#142]

**Comment by Woseseltops** [comment]
For completeness, Habtom suggest to rename these buttons: 'Save & Add, Save & Continue, Save' . While it's nice and short, I fear these names might confuse new users.

**Comment by Elisagig** [comment]
Dear Colleagues,

I know you are busy working on the sprint, but my colleagues mentioned this as urgent related to  Save and Continue: 
When we do Create Linked Author,  Author's Name and then Save and Continue Editing, then go to "Author". there is a problem, it leads you to titles

Also when we want to add a new author and choose create we get a strange popup. Sometimes it gets solved and sometimes it comes back.   The problem happened last time on 15 April

**Comment by Woseseltops** [comment]
We will do this as hotfix so the team does not have to wait until the sprint is done.

**Comment by Elisagig** [comment]
Thanks a lot

**Comment by Mergpijp** [comment]
Okay I think I have hopefully fixed the issue just note me when there is something as this is quite experimental.

**Comment by Elisagig** [comment]
Thanks
