### ISSUE TITLE
Access to edit pages for authors, translators and uploaded files, directly from a publication

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#145]
That is, an edit button for each linked object. Right now, it is only accessible from the search results when making a new link (so there is a workaround: unlink and link again), but we want to solve it the pretty way.

The best way would be to have the 'side step' edit view as a modal, but @Mergpijp indicates this leads to problems... so let's start with opening it as a seperate tab.

**Comment by Woseseltops** [comment]
Just discussed: we will start with the workaround for now.

**Comment by Mergpijp** [comment]
With the workaround this is done. The issue remains..

**Comment by Woseseltops** [comment]
Today in the demo this was not yet there!

**Comment by Mergpijp** [comment]
This was done but on a branch that i lost. Redeploying now.

**Comment by Woseseltops** [comment]
Verified that this is live now.
