### ISSUE TITLE
When creating/editing publications, also show the image contents of the uploaded files in the table

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#147]
Request by Habtom

**Comment by Woseseltops** [comment]
Keeping this out of the sprint for now because it is already quite full, but I'm guessing that this is quick thing that can be included if we're running out of issues.

**Comment by Elisagig** [comment]
For following sprint maybe?  We got related issues again 
Habtom: 
"After creating images, I want to edit and re-edit the image titles while staying in the Create Page but this is not working".
Issue reported yesterday

**Comment by Woseseltops** [comment]
@Mergpijp says this is finished, will be available next deploy.
