### ISSUE TITLE
Expand comments section

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#149]
Hi

I remember posting this issue but can't find it yet. We would like to expand the comments section because it is not enough to fill in the text and what we want to say.

**Comment by Mergpijp** [comment]
Ok anything specific? What more?

**Comment by Elisagig** [comment]
Just to make the comment section wider because it is too small for the text my colleagues are adding

**Comment by Woseseltops** [comment]
@Mergpijp indicates this is done, will be available at next deploy.
