### ISSUE TITLE
Word correction: Translated? Yes/No

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#15]
Is it translated? 
In the view part of "Is it translated?" it is wrong to say "true"

Graag dat veranderen naar: "Yes" in de plaats van "True" 

Bedankt

**Comment by Mergpijp** [comment]
Okay changed to: Unkown, Yes, No

**Comment by Mergpijp** [comment]
I misread it is only for in the view, done this.
