### ISSUE TITLE
Currencies

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#150]
My colleagues are saying that some money currencies are not available in the database. Some old currencies for example. Could you upload such a list?

**Comment by Woseseltops** [comment]
Sure @Elisagig , just let us know what you want.

**Comment by Elisagig** [comment]
Prima. Will ask them

**Comment by Elisagig** [comment]
Sorry I forgot to get back on this point. I mean Deutsche Mark, Dutch Gulden, and other older currencies in Europe

**Comment by Mergpijp** [comment]
Added old European currencies and non Euro european currencies.

**Comment by Woseseltops** [comment]
Will be available at next deploy.

**Comment by Woseseltops** [comment]
Was not available today during demo... @Mergpijp has a method so this can make it into production as promised.
