### ISSUE TITLE
Layout problem in showing entries

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#151]
Dear Colleagues,
We have this problem that we hope to be solved before our meeting on the Advisory Board tomorrow, so before 16:00.  This was reported by my colleague Matija. 

From Navigate, when you go to specific categories, such as language, genre, keywords, etc., and you choose one of these and then click on 1 entry - e.g. language - Arabic (standard), to see all the publications that are in Arabic, you get 3 pages of publications. But when I click on 'next' to go further, then it switches to the general overview list, and suddenly there are all 14 pages of all publications. This happens with all categories that I've tried.

A different thing happens when I choose Author; whatever name I click I get this error.
<img width="934" alt="Annotation 2021-04-30 103751" src="https://user-images.githubusercontent.com/61408472/116673297-8325fb80-a9a3-11eb-958b-c01217bc6892.png">

**Comment by Woseseltops** [comment]
This will be deployed as hotfix. Really important for @Mergpijp to make sure he doesn't accidentally deploy his work on sprint 2 (https://github.com/Mergpijp/GlobalOrthodoxy/milestone/2  ).

**Comment by Elisagig** [comment]
Thanks
