### ISSUE TITLE
Bug under Collection Info

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#155]
Under Collection info and then Contact Website:If you press "Enter" after you pasted a website-link, you get an error message; see below:
![image](https://user-images.githubusercontent.com/61408472/120185616-bbbf2c00-c212-11eb-9ae6-0cca0bc9d08e.png)

**Comment by Mergpijp** [comment]
This seems to be similar to #173  and solved? hotfix got deployed

**Comment by Elisagig** [comment]
Yes. This is fixed We can close this
