### ISSUE TITLE
Possibility to edit from a different place

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#157]
My colleagues are requesting for a possibility to edit image-title and Image-title/contents and Author/Translator from here
  
![image](https://user-images.githubusercontent.com/61408472/120187262-df837180-c214-11eb-924b-4393abfc9a95.png)

![image](https://user-images.githubusercontent.com/61408472/120187291-e4e0bc00-c214-11eb-8faf-d635514675ce.png)

**Comment by Elisagig** [comment]
So from here
![image](https://user-images.githubusercontent.com/61408472/120786017-064fe980-c52e-11eb-8e76-3765dad19c4a.png)

Instead of from here
![image](https://user-images.githubusercontent.com/61408472/120786044-0ea82480-c52e-11eb-8e66-52c17c081e42.png)

**Comment by Mergpijp** [comment]
This should have been solved earlier? I dont see the edit button in your image but it exists now.

**Comment by Elisagig** [comment]
Yes if it is working to edit it from up instead of down we can close it

**Comment by Woseseltops** [comment]
@Mergpijp says this done, will be available at next deploy
