### ISSUE TITLE
Layout name

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#159]
According to my colleagues: It is not a bid deal but esthetically we may remove the redundant “name” in this (and some other places, apologies, I don’t remember now.  

![image](https://user-images.githubusercontent.com/61408472/120786167-3a2b0f00-c52e-11eb-9012-d8472339d7a5.png)

**Comment by Mergpijp** [comment]
Ok removed name from multiple fields/classes.

**Comment by Woseseltops** [comment]
@Mergpijp indicates this is done, will be available at next deploy.
