### ISSUE TITLE
Search filters do not always work properly yet

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#164]
For example, when I search for the 'pope', and say it's a keyword, I also get results where that don't have 'keyword' in the row 'search term appears in'.

**Comment by Mergpijp** [comment]
In development this example seems to be working? Does it have to do with #166?

**Comment by Mergpijp** [comment]
There seems to be a difference on the production server and the development server

**Comment by Mergpijp** [comment]
The search term is in content_description but it is not showing..

**Comment by Mergpijp** [comment]
I think I got it. It checked if string contains in search_term_appears_in but I need to check the index only so: search_term_appears_in[index]. A stupid typo.

**Comment by Woseseltops** [comment]
Seems to work for the first page, but not once you click 'next'.

**Comment by Mergpijp** [comment]
This is solved I needed the variables in context so that next or pevious hold the settings

**Comment by Mergpijp** [comment]
The hidden get variables are without underscore '_'. I added a underscore and it seems to be working now.
