### ISSUE TITLE
Fix errors when clicking 'next' in the list view

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#166]
* When searching for a publications, using search term "arabic"
* When searching for files, clicking 'next' loses the query

**Comment by Mergpijp** [comment]
The error is not very clear. I do not know what to do here.

**Comment by Mergpijp** [comment]
It is a strange thing since this has been working before

**Comment by Woseseltops** [comment]
Verified that both bullets are solved!
