### ISSUE TITLE
When searching for countries and cities in a publication, make results appear after 1 character instead of 3

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#167]

**Comment by Mergpijp** [comment]
The search works but it is case insensitive making capital letter N not resulting in Netherlands.
I do not know how to make it case sensitive.

**Comment by Mergpijp** [comment]
So the thing we wanted is : name_startswith this way one gets Dutch when D is the input. This has been solved.

**Comment by Woseseltops** [comment]
Will be available at the next deploy
