### ISSUE TITLE
Affiliated Church: Editing and new entry

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#17]
Under "Affiliation" we want to make a change.

Please enter an extra box saying "Extra Info. Church"

**Comment by Mergpijp** [comment]
You can add church objects yourself, maybe i did not understand what you meant?

**Comment by Elisagig** [comment]
I mean that we want there a 3rd open box that allows Habtom and Emanuelle to add any extra info they need about the churches. Een beetje zoals de "comments"box.

**Comment by Mergpijp** [comment]
Oh okay for the record I am Emmanuel, you meant Matija I think. This will be easy though.

**Comment by Elisagig** [comment]
So "Donor" then "Affiliated Church" then a 3rd box saying "Extra Info."

**Comment by Elisagig** [comment]
> Oh okay for the record I am Emmanuel, you meant Matija I think. This will be easy though.

So sorry I mixed up the names. Yes, end of the week confusion. :)

**Comment by Elisagig** [comment]
Sorry also for misspelling your name. 👎

**Comment by Mergpijp** [comment]
This is done deploying soon.
