### ISSUE TITLE
Dollar currency not first

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#170]
Dear colleagues,

Today we had a meeting and some of my colleagues complained that they do not want the dollar currency to appear in the beginning. They prefer at the beginning to see "Unknown" and then Euro and after that the other currencies. Also posted a former issue previously on currencies. They want the old currencies like the Dutch currency before the EU etc

**Comment by Mergpijp** [comment]
Changed the order of the currencies.

**Comment by Woseseltops** [comment]
Let's make this a hotfix, deploying this should fix the fact that the users did not have access to #150 as well.

**Comment by Woseseltops** [comment]
@Mergpijp says this is done, will be availble at next deploy.
