### ISSUE TITLE
Some parts not open to public

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#171]
My colleagues reminded me today to remind you that when the website is public we do not want the info with the phone numbers of the people (under Collection => Currently owned by) to appear to the general public. Also the team comments should be for us only and not for the whole public

**Comment by Mergpijp** [comment]
I will look for a logged in user at the publication detail.

**Comment by Mergpijp** [comment]
You asked me before for the collection date. I have added user.is_authenticated for team_comments and currently_owned_by variables in the publication_detail view.

**Comment by Woseseltops** [comment]
For completeness: this can't be verified right now, as the detail page is not available at all when logged in. Still, the code is there under the hood.
