### ISSUE TITLE
Page Error Under Edit Author

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#173]
When you click on a publication
Then click on Edit
Then write an author under "Search Authors" and enter, you get an error page
https://globalorthodoxy.cls.ru.nl/publication/651/edit/?next=/
![image](https://user-images.githubusercontent.com/61408472/123410640-d71e1c80-d5af-11eb-82b5-9b31ebff5e91.png)

**Comment by Mergpijp** [comment]
Yes has to do with the form being invalid but still valid because of no requirements. It redirects to nothing so I disabled the enter button all together.

**Comment by Elisagig** [comment]
Thanks :)

**Comment by Woseseltops** [comment]
@Mergpijp mentions this is done and deployed

**Comment by Elisagig** [comment]
Great. Thanks
