### ISSUE TITLE
Support periodicals from the detail view

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#177]
Similar to the edit view, make sure only the appropriate fields show up, depending on whether something is a periodical or not.

**Comment by Mergpijp** [comment]
strange this seems already there? Is it not working correctly then?

{% if object.publication_year and not object.is_periodical %}
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-light"> 
    <tr>
        <th>publication year</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>{{object.publication_year}}</td>
    </tr>
    </tbody>
</table>
{% endif %}
{% if object.is_periodical %}
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-light">
    <tr>
        <th>Start year</th>
        <th>End year</th>
        <th>Ongoing</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>{{ object.start_year }}</td>
        <td>{{ object.end_year }}</td>
        <td>{{ object.ongoing }}</td>
    </tr>
    </tbody>
</table>
{% endif %}

**Comment by Mergpijp** [comment]
Just tested this it seems fine?

**Comment by Woseseltops** [comment]
I guess you're right @Mergpijp . Sorry!
