### ISSUE TITLE
In the list view, remove the 'end year' question mark if something is a periodical

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#178]
This should be all that is needed to add support for periodicals to the list view.

**Comment by Mergpijp** [comment]
you mean when something is on_going?

**Comment by Mergpijp** [comment]
I kind of forgot were we talked about and there is no note I dont know if this is correct

**Comment by Woseseltops** [comment]
@Mergpijp indicates this now works (fixed while talking about it :) ) , will be deployed along with the rest of the sprint today.
