### ISSUE TITLE
Image details => new box

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#18]
Under Content => Image Details 

We need that that box opens up into a new box that includes the following info:

Name of source:  

Contact of source: 

Copyright issues: 

Is there a way that the system knows the size of the photo automatically?

**Comment by Mergpijp** [comment]
Size as in kilobytes? or dimensions? Can be done with external libraries.
As I understood you want a many to many field with Image details containing 3 fields (name of source, contact of source, copyright issues). Or just a foreign key (onetone relation) like city or country for example.

**Comment by Elisagig** [comment]
Many to many: I will ask the team what can be added here and get back to you

Size as in dimensions

**Comment by Mergpijp** [comment]
Ok this is implemented waiting for further notice

**Comment by Elisagig** [comment]
Yes. Na overleg met team: when you click on that, a box opens that has 2 boxes: 
1. Source of photo/illustration
2. Photographer 

In the future we will add "copyright" here but not now

**Comment by Mergpijp** [comment]
okay, had change implementation.
