### ISSUE TITLE
In the list of authors, add the churches

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#180]
For each author, go over all publications, and see which churches are connected to this publication. Don't save this in the database, but do this on the fly each time (so it's always up to date).  Add the results to a separate column that can be sorted.

Next step could be to really filter on it.

**Comment by Mergpijp** [comment]
I do not know how to sort a context field in django

**Comment by Woseseltops** [comment]
@Mergpijp says this is done, will be available at next deploy.
