### ISSUE TITLE
Public front page

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#184]
Something like this, but with more images:

![image](https://user-images.githubusercontent.com/1909317/128509733-601b4f75-3f2c-4125-9be8-79c84db129da.png)

Might lead to performance issues, so maybe come up with some mechanism to automatically make smaller, square versions of images.

**Comment by Woseseltops** [comment]
Maybe even cooler, if you have more time: make them slowly scroll left, so you see an never ending stream of books pass in front of your eyes.

**Comment by Woseseltops** [comment]
Idea by @Mergpijp , inspired by Netflix (make the books dark, put text on top of it): 

![Uploading image.png…]()

**Comment by Woseseltops** [comment]
Todo:
* Make it so it fills the whole screen
* Background (= borders between images) black
* Large centered title in white, on top of the images
* Transparant background below title but above images

Optional:
* Experiment with CSS skew
* Automatic scrolling

**Comment by Woseseltops** [comment]
Change of plan:
* Make it so it fills the whole screen
* Background (= borders between images) black
* Large centered title in white, above the images
* Ordered by recency

**Comment by Woseseltops** [comment]
Extra thing: click to detail view

**Comment by Mergpijp** [comment]
Should I ask C&CZ about the missing files? I dont know how to cope with this.
