### ISSUE TITLE
Author name + original language

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#19]
Under "Author name" we want to do 2 things: 

1>Kindly add a box under it saying "Author name original language"

2> Kindly replace "Date of Birth" of author by the title "Extra info. Author" and this then becomes **not** a numerical field

**Comment by Mergpijp** [comment]
I ques the same is wanted for translator?

**Comment by Elisagig** [comment]
Yes good idea.

**Comment by Mergpijp** [comment]
This is done will be deployed soon.
