### ISSUE TITLE
New publication entry problems: prefilled parts 

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#191]
Dear Colleagues,

Sorry to disturb during your vacations but kindly check the following:

Message from Habtom:
1. "When you open New Publications, you get a prefilled window, filled by the last entry. In my case it was the last entry by Matija. So in my desperation, I thought to enter a new publication by clearing the prefilled window. The result is a disaster: Matija's entry was replaced by mind. 

2. The prefilled part is not only for the Titels but for all 10-tabs like Author, Language including comments...
We couldn't change city, country and and we couldn't enter new ones.

**Comment by Mergpijp** [comment]
This should be deployed and disabled drafting functionality.

**Comment by Elisagig** [comment]
Thanks.
