### ISSUE TITLE
Two  books, unable to edit

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#197]
Last issue reported by Habtom, also on Slack:

"I see two books without any front page. I thought maybe I can retrieve the files somehow by going to Edit... Alas, I get error message.
As far as I know, the error message after pressing Edit happens only to these two files."
![2021-10-14 09_25_49-GeezIMEServer](https://user-images.githubusercontent.com/61408472/137459832-a7f1b45c-dd7e-42e7-b3a8-82af3377b2d2.png)

**Comment by Mergpijp** [comment]
This is done
