### ISSUE TITLE
Not clickeable

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#202]
In our working database when you click on "navigate" and then "church" for example, you see everything but in the Public Database if we choose "church" then the name of the church it is not clickeable. It does not work. We do not know why. Is there a broken link maybe or misunderstanding or not done?

**Comment by Mergpijp** [comment]
Ah yes this was not implemented which could be done you want it done?

**Comment by Elisagig** [comment]
Yes please

**Comment by Mergpijp** [comment]
This is done. Took just 20 minutes or so..
