### ISSUE TITLE
Can't log into the Database: Access Denied

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#208]
Both versions of the Database (working version and public version) are not opening. It is saying "Access Denied". Thought it was just me but other colleagues have that problem as well.

**Comment by Woseseltops** [comment]
This was discussed via email!

**Comment by Elisagig** [comment]
Thanks Wessel. Just reported something on Github. Kindly check.

Happy weekend,


Elise

________________________________
