### ISSUE TITLE
Zooming in photos when opening

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#217]
Some additional attached files on the Database cannot open up to be bigger, so I mean you cannot zoom them in. For example this one (not the cover page but the other attached pics below). Do we keep them like that or do we ask Wessel to do them in a way where they become clickable for a bigger view? Or is this to protect them (e.g. Copyright)?
|https://globalorthodoxy.cls.ru.nl/new/publication/15/detail_view/ (edited) 
2. And another thing is that some photos are not showing, for example this Syriac one
https://globalorthodoxy.cls.ru.nl/new/publication/17/detail_view/ (edited) 
And this one as well has no photo
https://globalorthodoxy.cls.ru.nl/new/publication/23/detail_view/

**Comment by Woseseltops** [comment]
> Do we keep them like that or do we ask Wessel to do them in a way where they become clickable for a bigger view?

Haha let me know what you decide :). 

>  And another thing is that some photos are not showing, for example this Syriac one

Ah yes these publications have no photos attached, but that looks a bit weird in the public view. Shall I remove he 'empty' pictures?

**Comment by Elisagig** [comment]
1. Regarding the "Empty Pictures" these were publications that Heleen and some other colleagues uploaded and thought they will add the pictures later. I will remind them to do that.

2. Sorry, pasted the thing and forgot to delete the part about you. Yes we want to make them clickable. Meaning that the user can open them and see the pics 

Thanks

**Comment by Woseseltops** [comment]
Okay I made it open in a separate tab. Let me know if this works for you @Elisagig !

**Comment by Elisagig** [comment]
Thanks
