### ISSUE TITLE
Titles disappearing

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#237]
Message from Habtom
"The last book that I have uploaded today was uploaded in 2020 but somehow disappeared. The name of the author was still in the database".

**Comment by Woseseltops** [comment]
Hmm weird, not sure how this can happen. Did reuploading help?

**Comment by Elisagig** [comment]
I can ask him now

**Comment by Elisagig** [comment]
He says it is solved and he reuploaded it. Thanks
