### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#25]
Forgot to ask when we want to improve the layout (design of the website) to make it look more appealing to use for the audience. Thanks ;)

**Comment by Mergpijp** [comment]
What about a RU logo in the banner and changing the blue colors into red? This is very basic but I do not know what to do really.

**Comment by Elisagig** [comment]
Nice idea

**Comment by Mergpijp** [comment]
Done this and is deployed.

**Comment by Elisagig** [comment]
Cannot see it yet

**Comment by Mergpijp** [comment]
That is strange, i can see it when i got to https://globalorthodoxy.cls.ru.nl/ . There is a radboud logo in the uppper banner, and color scheme turned to red. Not much changed.

**Comment by Elisagig** [comment]
ok
