### ISSUE TITLE
General comments for public

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#27]
Kindly open a general comments field that the public can fill. This is for us now but when it is open people can share their comments down the page

**Comment by Elisagig** [comment]
Heleen is saying we can open it now to be filled in but when the site is more visible it can be seen a d she says it can be in the same place as the earlier one (comments)

**Comment by Elisagig** [comment]
See number #28 to learn what she means by the "earlier one"

**Comment by Mergpijp** [comment]
So to get things clear you want people to have acces to the publications. And then at the publication view (detail) add some comments for the public?

**Comment by Elisagig** [comment]
Hi I met with the team and will clarify everything now with new issues
