### ISSUE TITLE
Keywords icon disappears

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#273]
When we click on the left on "Keywords" then the icon that you click on disappears. So you cannot find it

**Comment by Woseseltops** [comment]
You mean in the public view? I'm surprised the keyword icon was still there, because Heleen asked me to remove it ;) . If you still see the keyword icon, and do CTRL+F5, do you still see it?

**Comment by Woseseltops** [comment]
Okay, nevermind, the menu bar on the grid was not updated yet. Just fixed that!
