### ISSUE TITLE
Separate first and last name of authors

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#29]
Heleen suggests separating the first and last name of authors and she is not sure we need a "list" of authors. Automatic suggestions is enough she thinks

**Comment by Mergpijp** [comment]
Okay, so a one-to-one relationship and firstname and lastname are you sure? Because we had this before.

**Comment by Elisagig** [comment]
Ok will ask her tomorrow at 11
