### ISSUE TITLE
"Search" button works but should not be case sensitive 

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#31]
Keep search button on the top right of page but make it not case sensitive. 

The search button on the top right works but should not be case sensitive. (e.g., the system won’t recognize prophet if the publication title contains Prophet, or sifr/Sifr…). Keep this search button on the top right but make it not case sensitive so open both to capital and small letters.

**Comment by Mergpijp** [comment]
Ok will look into this and deploy later.

**Comment by Elisagig** [comment]
Great

**Comment by Mergpijp** [comment]
This was difficult because I use regular expressions. Fortunaly there was a function iregex instead of regex which is case-insensitive. Wanted to adjust the regular expression wasted some time here, but it works! Will be deployed later!
