### ISSUE TITLE
Under "Titles" new change

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#32]
A. We want to change the "Titles" page. So instead of "Title Original", "Title Transcription", "Title European","Title Translation" we will remove "Title European" so it will be like this: 

Title

 Transcription

Translation

+ Add new Title

B,. We want to add the option "Add New Title" and under that we want to have again "Title, Transcription, Translation" and then another possibility to add more titles under one book because some books have more than one title

**Comment by Mergpijp** [comment]
I see what you mean, but this can be better done if we use a plus box. So one can add multiple titles to  a publication. Let me know if this is a good idea.

**Comment by Elisagig** [comment]
Yes good idea. That is it. A plus sign but then again saying Title, Transcription and Translation another time so the students do not forget to add them in.

**Comment by Elisagig** [comment]
Hi Emanuelle, 

I do not see this new change. What we meant was: 
"Title" 
"Title Transcription"
"Title Translation" 
and then a box underneath saying "+Add New Title" 

This happens under titles

**Comment by Elisagig** [comment]
This is an important point and we find it an issue of priority. If it is not clear please call me on my mobile

**Comment by Mergpijp** [comment]
I do get what you want, only this requires formsets which i have no experience in. So i will ask someone.

**Comment by Mergpijp** [comment]
Do you expect it to have more then 3 titles? Or do you expect publications with tens of titles?

**Comment by Elisagig** [comment]
No around 3 or 4 titles normally (5 max I think) (because some publications have titles in 2 or 3 languages with different titles so we decided to do it this way)

**Comment by Mergpijp** [comment]
Ok have been thinking about the implementation of this. So if the user starts typing in the firstt three titles the next three titles will appear and so on. Not sure if it is going to work but this is what I think.

**Comment by Mergpijp** [comment]
Ok this is done, took my time but done.

**Comment by Elisagig** [comment]
Great. So proud of you.
