### ISSUE TITLE
Content words open to add and not limited to list + separate by semicolon

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#33]
Under content: make “Keywords” open for us to add and not limited to this plus list and separated by semicolon to make it clear.

**Comment by Mergpijp** [comment]
This can be done better: [see](https://select2.org/tagging#tagging-with-multi-value-select-boxes).
Ill implement this as I think this is what you mean.

**Comment by Mergpijp** [comment]
Strange cannot get this to work with django. Will discuss this later.

**Comment by Elisagig** [comment]
Yes thanks

**Comment by Elisagig** [comment]
Bedankt

**Comment by Elisagig** [comment]
Team is asking: The keywords should not double with the information that we already include elsewhere in the db.

**Comment by Mergpijp** [comment]
The keywords field shows a list of all keywords that exist for every publication. You want that?
Should the application filter out other information if it is elsewere? Were do you mean exactly?
Have been delfing deeper into the documentation but cannot get this to work. Made a bugreport for this see [link](https://github.com/applegrew/django-select2/issues/603).

**Comment by Elisagig** [comment]
Ok just asked the team for more clarity. So basically what is asked in this question is the following:
1. Instead of a dropdown menu for keywords a semi colon so like "Bible; New Testament; Prayer" 

2. Yes, as you mention, to have a list of all keywords that exists in publications so we don't type them in each time.

3. That the keywords that had been added previously show when we try to type them or that we know in a way they exist so we don't have to type them in twice.

**Comment by Mergpijp** [comment]
Yes this is exactly what I am implementing. My question is getting answered and hopefully it will work.

**Comment by Mergpijp** [comment]
So I solved this however true numbers (integers) cannot be tagged but you can tag a name with a number. Will be deployed soon.
