### ISSUE TITLE
Delete "Image Details" 

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#34]
Leave out “image details”. Keep only “Description of Illustration”

**Comment by Mergpijp** [comment]
Okay clear, will be deployed later.

**Comment by Elisagig** [comment]
Hi we do not see this change. So basically under "Add New Publication" =>"Content" => Remove "Image Details" box.

**Comment by Mergpijp** [comment]
It is removed but not yet deployed.

**Comment by Elisagig** [comment]
When do you expect the things to be deployed? Thanks
