### ISSUE TITLE
Collection info only for team

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#35]
Collection info stays but in future will be only for the team and not for the public. Just informing and checking. Thanks

**Comment by Mergpijp** [comment]
Ok will note that keep the issue open.

**Comment by Elisagig** [comment]
Ok

**Comment by Mergpijp** [comment]
The same goes for Other comments?

**Comment by Woseseltops** [comment]
The website is only visible for logged in users, so issue seems redundant for now.
