### ISSUE TITLE
Under "Collection Info" create more space for "Comments"

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#36]
Under Collection info. Create more space for “Comments”. It is very limited. Make it wider (to be able to add in more text)

**Comment by Mergpijp** [comment]
I just moved the whole comments so it is no more in Collection Info. Is this what you want?
Sorry but this issue is counterintuitive to #37 .

**Comment by Elisagig** [comment]
Yes good. I meant move and create more space (more than 400 characters)

**Comment by Mergpijp** [comment]
Yes, now changed to textfield instead of charfield. Has a much bigger box.

**Comment by Elisagig** [comment]
Great. Thanks
