### ISSUE TITLE
Make New Column after "Files" called "Comments" 

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#37]
Please move the “Comments”to a new column called “Comments” after “Files”. It will include more space than before and should include 2 tabs: 
General Comments.............................

Team Comments .........................

(Other Comments is for team only and not accessible to the public)

**Comment by Mergpijp** [comment]
Okay this should be doable, deploying later.

**Comment by Mergpijp** [comment]
What do you mean by 'it will include more space than before'? You mean more characters? It is already 400.

**Comment by Elisagig** [comment]
Yes more characters please. The students feel the maximum amount to write in that field is too short

**Comment by Mergpijp** [comment]
Okay this is done. Should I add Other comments to? under the same column?

**Comment by Elisagig** [comment]
Yes

**Comment by Mergpijp** [comment]
Okay this is  done the permissions will be set later.

**Comment by Elisagig** [comment]
Thanks you rock
