### ISSUE TITLE
Uploading files should be easier

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#38]
Files. Uploading of files can happen differently in terms of Naming of files. Other way?

**Comment by Mergpijp** [comment]
You mean that there is some gibberish at the end of a filename if the filename is already taken?
I will try to search for this or otherwise discuss this.

**Comment by Mergpijp** [comment]
Okay i found this [link](https://stackoverflow.com/questions/46184823/preventing-a-file-upload-completely-if-file-already-exists-in-django/46185044), the user gets an error if the file already exists.
Is this what you want?

**Comment by Elisagig** [comment]
Yes and they are saying that the file name appears weird and long. That it could happen in an easier way where the name of the file itself appears like when you are generally uploading files.

**Comment by Elisagig** [comment]
To be honest I don't remember them mentioning if the file already exists but rather the team referred to long weird names of automatic titles instead of a one keyword name that we normally do when we upload files

**Comment by Elisagig** [comment]
Managed to solve this? They want the naming to be done in a different way and in such a way where we can give them names and manage to find them later. Thanks

**Comment by Mergpijp** [comment]
I have been trying several options but someone from  the TSG has already done this so I should ask him. Since it is a bit complex of a issue.

**Comment by Mergpijp** [comment]
So I got response from two of the TSG members. And I fixed this by appending the date to the file path. This way the filename can be anything at all.

**Comment by Elisagig** [comment]
Thanks
