### ISSUE TITLE
Change "Submit" Button

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#39]
Submit button should not bring you back to beginning. You need one “back” and one that is called “next”. Prefer to replace it with “Save” and you stay on the same page.

**Comment by Mergpijp** [comment]
So  there is three buttons? Back will take you to the show page? And next will take you to the search page? And Save will do nothing but save? Just tell me were to go it is unclear now.

**Comment by Elisagig** [comment]
Back should take you to the former page

Next should take you to the next page 

And save should save the current page 

The team do not like the word "Submit" they say it is not so precise

**Comment by Elisagig** [comment]
How is it working?

**Comment by Mergpijp** [comment]
Hmm, I am stuck at the save button. It keeps redirecting the page while this is not desirable.

**Comment by Mergpijp** [comment]
Ok I am done. I made save so that it goes to the edit page so it makes a new object just like next. Only now one can remain editing the publication. This is what was intended I think.

**Comment by Elisagig** [comment]
Thanks

**Comment by Elisagig** [comment]
My colleague Habtom is asking me about the "Next" and "Previous" buttons. Here is what he is saying:

"whenever I edit something and want to go the previos page, then I have to go out and start anew. For example I just have added Rotterdam, The Netherlands as publication city and country respectively. Then I see only Sumbit at the bottom: no forward or backward, no next buttons. Because I want to continue with entries to the same book. I press sumbit, then I come to the Add New City page. To go the where I was, to the book, I have to go back to Publications, go to Last (page 3 in this case) and select my book and edit; and move on"

**Comment by Mergpijp** [comment]
I do not understand. If your editing/ creating a publication one can simply close the window after adding publication cities. The main publication window will dynamically update the new city, so you can continue. I do not understand that you go back to the title page and select the book while this is unnecessary.

**Comment by Elisagig** [comment]
By that he means that once he edits something he cannot continue with filling entries on the same book but each time he ends up in a totally new "add new Publication" page instead of just continuing what he was doing. Clear now?

**Comment by Mergpijp** [comment]
Needed to think about it.. But you can continue filling entries if you close the popup page. The new entries will be added dynamically in the field. So no I still don't get it. (Was busy with other issues).

**Comment by Elisagig** [comment]
What we mean is if you add an entry and you want to edit it the "Next" and "Back" only take you to the main list and not the next tab in the column. Ok I give an example: Let us say we are in "Language" and you want to go to the previous table "Author" and you click on "Previous" you do not end up in "Author" maar helemaal in het main list list van publications. Bijvoorbeeld ook als je dan op "Publishing Information" bent en je klikt op "Next" dan ben je niet in de volgende entry "Affiliation" maar dan weer naar de general lijst van andere publicaties. Je kan wel proberen en zien.   
Dus je kan niet gaan direct van Author naar Language naar Publishing Information met de "Next" en "previous" buttons

**Comment by Mergpijp** [comment]
Ok I understand this finally. You want a different functionality of the next and back buttons. If your in the last tab and your press next do you want to go to the titles page? And if you are at the first tab and press back do you want to go to the titles without saving the publication entry?

**Comment by Mergpijp** [comment]
But the question remains: Why would you want back and nex buttons when you can just click the tabs to fill in information?

**Comment by Elisagig** [comment]
Ok will tell them and get back to you on this

**Comment by Elisagig** [comment]
Asked the team and they say it is now not necessary and the buttons then have no need because the initial idea was that it takes them to the previous page they were in. Thanks

**Comment by Mergpijp** [comment]
for eidting publication the save button just saves and goes to the same page. Do you want it to go back to the page it came from?

**Comment by Elisagig** [comment]
Yes

**Comment by Mergpijp** [comment]
Yes this is referenced in another issue  #107. Will be deployed later.

**Comment by Elisagig** [comment]
Thanks
