### ISSUE TITLE
Make search handle exotic letter combinations

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#4]
Quote from Matijah: 

> Basically, if someone wants to search for “مزامير” (mazāmīr) or “صلوات” (ṣalawāt), they should be able to get the search results by only typing for instance “mazamir” and “salawat”.

š = sh
ṣ = s
ḍ = d
ṯ  = th
ṭ = t
ẓ = z
ġ = gh
j = g / j   (I mean they might either type it as g or j)
ḵ = kh 
ā = aa/a  (I mean they might either type it as aa/a)
á = a /aa / ae  (I mean they might either type it as a or aa or ae)
ī =ee / i /ie  (I mean they might type it as ee or i or ie)
ū = u/ou/oo/o/oe  (so one of those options)
ʿ = '/3 (so either ‘ or 3)
ah = a /ah 
dh = th /ḏ
ḥ = h

**Comment by Mergpijp** [comment]
This works now
