### ISSUE TITLE
Add New Publication

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#41]
Make “Add New Publication” button to be added after view “Publication” and under navigate in a way that is more visible

**Comment by Mergpijp** [comment]
Ok the first part I dont get. The second part is that you want 'Add New Publication'  in the navigation list? This can be done.

**Comment by Elisagig** [comment]
Thanks. Yes a link under navigate that redirects you to "Add New Publication" so when you click "Navigate" there is a button that gets you directly to add new publication rather than going to publication and then to add. Clear?

**Comment by Mergpijp** [comment]
yes if there is nothing more its clear.

**Comment by Mergpijp** [comment]
This is done, will be deployed later

**Comment by Elisagig** [comment]
Sorry I had misunderstood. They want it next to "Navigate" in the top header and not under it

**Comment by Mergpijp** [comment]
Ok will fix that then.

**Comment by Elisagig** [comment]
Thanks
