### ISSUE TITLE
Tag last name?

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#42]
The team is asking: "Is it possible to tag the last names and alphabetize them at a later stage to then be more easily searched?"

**Comment by Mergpijp** [comment]
So for this to be possible to work I need lastname to be seperated from firstname.
You made an earlier point about that if I remember correctly. You want to tag them in the search bar? I dont think it is possible. Not sure though what you mean.

**Comment by Elisagig** [comment]
What we mean is that for the author name of "Albert Soliman" for example if someone searches under say "Albert" or "Soliman" they can still be found in the search bar.

**Comment by Mergpijp** [comment]
I tried this on the testing environment it already seems to work? Your goal is to find the publication that contains 'Albert' or 'Soliman'?

**Comment by Elisagig** [comment]
Yes and also to see them in a list later in an alphabetical order if we like

**Comment by Mergpijp** [comment]
I propose to use arrow icons in the table title labels to sort publications in alphabetical order one way or the reverse way.

**Comment by Elisagig** [comment]
Good idea :)

**Comment by Mergpijp** [comment]
This cost some time because I did not find the correct library but is done now. Will be deployed later.

**Comment by Mergpijp** [comment]
This wasnt done correctly. Now after lots of time it is done.

**Comment by Elisagig** [comment]
Thanks
