### ISSUE TITLE
Permission system

### ISSUE THREAD

**Issue by Mergpijp** [Mergpijp/GlobalOrthodoxy#43]
So for the globalorthodoxy webapplication there can be two kind of users:
Ones that can edit, delete and view the page And ones that can only view the publications and search.
Do they all need an account? Maybe those that can view and search are users that can come from anywhere in the web? Maybe it is to hard to make an account for every user. Or do we want a more secure solution?

**Comment by Elisagig** [comment]
Yes I agree so we (the team) have accounts (so we edit, delete and view) and the rest of the viewers just visit and search (without accounts and without being able to edit)

**Comment by Mergpijp** [comment]
Okay, I made it so that visitors can: view, search the database. This was relatively easy just making sure that I did not make a mistake will test now.

**Comment by Elisagig** [comment]
Thanks @Mergpijp. One more thing: Heleen said that some things need to be private for us as a team. So the public sees most things, but every now and then there are things that we do not share with the general audience.

**Comment by Mergpijp** [comment]
The web application is now closed for public I think this solves all issues?

**Comment by Elisagig** [comment]
Yes
