### ISSUE TITLE
Database name: Four Corners of the World Library

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#46]
The title of the Database. Dus de algemene titel van de database gaat "Four Corners of the World Library" zijn

**Comment by Mergpijp** [comment]
You mean the title that is displayed in the browser tab? Currently its: Global Orthodoxy

**Comment by Mergpijp** [comment]
Ok changed title of database tell me if more is needed.

**Comment by Elisagig** [comment]
Yes thanks a lot :)
