### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#47]
Hi Again Emmanuel,

The team asked me today to inform you that they are facing problems uploading pictures. I had sent smth about photos previously. Could you follow up on that? Bedankt

**Comment by Mergpijp** [comment]
Hi, hmm what did you sent? I can't remember.

**Comment by Elisagig** [comment]
Just sent a file with explanation by Prof. Heleen. It is in the email.

**Comment by Mergpijp** [comment]
hmm I cant see any emails. You sure you sent to : e.chamilakis@let.ru.nl ?

**Comment by Elisagig** [comment]
I had selected your name and my ru account showed u
[Working file database-setupImages-pdf's.pdf](https://github.com/Mergpijp/GlobalOrthodoxy/files/4835604/Working.file.database-setupImages-pdf.s.pdf)
p your student email. Forwarded it again from there. Here is a copy

**Comment by Elisagig** [comment]
There is another issue with photos. The team is saying they cannot be uploaded.

**Comment by Mergpijp** [comment]
The file you sent is more of a guideline how to name files which is entirely in your hands, correct me if im wrong.
Will see what goes wrong with uploading.

**Comment by Mergpijp** [comment]
Do not know what error message your getting when uploading a file but for me it works.

**Comment by Elisagig** [comment]
@Mergpijp I asked the team about it. They are saying that when they upload pictures it is taking them somewhere else. Heleen wants to explain what she means by talking to you and Wessel next week

**Comment by Elisagig** [comment]
Check my email and the We Transfer videos. There was a misunderstanding. Not everyone in the team knew it needs to be done in two steps (through going back and adding the uploaded pic on files). Is there a way to do it in 1 step? Thanks.

**Comment by Mergpijp** [comment]
Yes Elise this has been implemented recently they can now do it in one step but it still a bit rough.

**Comment by Elisagig** [comment]
Prima
