### ISSUE TITLE
Urgent: Photos: unable to upload

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#48]
Dear Emmanuel,

My colleagues contacted me about an urgent matter. They cannot upload photos. It is not working. Kindly solve the problem because they need to do that this summer.

**Comment by Mergpijp** [comment]
Okay because of server restart redis needed to be re-enabled. This might solve the issue.

**Comment by Woseseltops** [comment]
Hi @Elisagig , do you mean existing functionality is broken (for example because of an error message, like the one I showed in #49 ) or that the functionality is not there yet (there is general file upload functionality, but not specific functionality for photos)?

**Comment by Elisagig** [comment]
Hi @Mergpijp @Woseseltops some colleagues are saying they can now upload photos and others are saying they cannot. Apparently it is only working with only some types of photos. I do not know where the problem is lying. Kindly follow up. Thanks.

**Comment by Woseseltops** [comment]
Hey @Elisagig . Yeah we have still not been able to reproduce this. Is it possible to describe the steps you do that will consistently lead to the problem? And if not, can we plan a virtual meeting so you can show us?

**Comment by Elisagig** [comment]
How about meeting either next Friday the 23rd or on Monday/Tuesday any time after 11:00?

**Comment by Woseseltops** [comment]
@Mergpijp possiblly has found a solution for this: filename might have been too long.

**Comment by Elisagig** [comment]
So I close it?
