### ISSUE TITLE
Weird layout

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#49]
Dear Emmanuel,

My colleagues are saying there is a weird layout when you open the database. Like a yellow thing. I thought it might be a temporary things since you guys are working on the site. Could you check?

**Comment by Woseseltops** [comment]
Hey @Elisagig , are you referring to screens like this? 

![image](https://user-images.githubusercontent.com/1909317/85515860-e285e300-b5fd-11ea-9328-e9935b5221ad.png)

This is an error message indicating something is broken; it tells developers what when wrong and where to look for a solution. @Mergpijp : I think there is a problem connecting to Redis; maybe it is down after the Applejack restart?

**Comment by Mergpijp** [comment]
This is clearly a redis related issue. It is straightforward since the server has been restarted and should be solved now. If that is what @Elisagig  means.

**Comment by Elisagig** [comment]
Yes. I will ask the team if there are other things they are facing

**Comment by Woseseltops** [comment]
Please create separate issues if there are any other things :)

**Comment by Elisagig** [comment]
True. Will do that in Duryea
