### ISSUE TITLE
Global Orthodoxy : Geez again

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#5]
Thanks for this new world :) 

Message from Habtom on Friday at 15:10 "Dear Elise, Please ask Wessel and Emmanuel to implement Ge’ez in the database so that I can start entering texts in Tigrinya and Amharic"

So Ge'ez issues again

**Comment by Mergpijp** [comment]
Dear Elise,

There was a lot of mail traffic and there was some talk about this. Would you please be so kind to give some background information?

**Comment by Elisagig** [comment]
Even with the Geez software it is not working for Habtom to add script in Geez languages

**Comment by Woseseltops** [comment]
When it comes to Geez have three options:
1. Use applications Geezsoft (commercial) or Geezime (free). These cannot be integrated into the website itself, but can be installed by the user on the computer and should then work together with any website. The last message of @Elisagig suggests something is not working together, however.
2. Build something that **can** be built into websites from scratch (might take a lot of time and might not be needed). 
3. Use existing web code libraries like https://github.com/dawityise/Amharic-Keyboard .

Just talked with Heleen about this (and she will also inform Habtom), and for now we will try to make option 1 work. Emmanuel will contact Habtom to check what's not working for him right now.

**Comment by Mergpijp** [comment]
Contacted Habtom. He said the geez software (don't know which) is working right now. Closing the issue.

**Comment by Elisagig** [comment]
Thanks Wessel. Sorry replying only now. I am usually off Wednesdays and Thursdays. So you already discussed it with Heleen. Great
