### ISSUE TITLE
Is it possible to make photo of publication cover appear next to publication under search?

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#50]
Hi @Mergpijp. My colleagues asked for a layout-related question today. They are wondering whether it is important to see the picture of the publication cover that they uploaded next to the publication when you search for it, for example like books we search for under Amazon.com. Is that possible?

**Comment by Mergpijp** [comment]
I think it is possible yes. But need a distinct way of knowing what picture belongs to the cover of the publication. So how are you going to name it?

**Comment by Woseseltops** [comment]
Just a thought: maybe for each publication, it lists all images that have been uploaded as files (recognized by the file extension?) and users can select which one they want as the 'main image' shown in the list view? If there is only one, it of course selects that one.

**Comment by Elisagig** [comment]
Yes sounds good. If there is an option saying: "show as cover"

**Comment by Mergpijp** [comment]
Okay, this was easier then I thought. Each publication has a select2choice field were exactly one file can be chosen as cover file.  The file needs to be created first or existing. Thats why it is places after the UploadedFile field. The template does the rest of the work.

**Comment by Mergpijp** [comment]
Will be deployed later. Note that any existing file can be chosen even if it does not belong to the publication. It was to hard to solve this because one cannot know which files belong to a publication that is still under construction.

**Comment by Elisagig** [comment]
Thanks :)
