### ISSUE TITLE
Fix permissions of uploaded files

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#51]
Apparently, when files are uploaded, they don't always:
* Have the same owner and/or group.
* Might have their ACL masks set incorrectly.

This is what needs to happen:
* Run a command so that all files have the correct permissions again.
* Make sure that everything is correct automatically for newly uploaded files.

**Comment by Mergpijp** [comment]
I tried multiple things keer getting operation not permitted.
https://www.computerhope.com/unix/usetfacl.htm

**Comment by Mergpijp** [comment]
This seems to have to do with vassals not working. So Micha is looking into this.

**Comment by Woseseltops** [comment]
We looked at it together today and concluded:
* The main problem is that some uploaded files have their mask set in a weird way. We cannot reproduce this, but @Mergpijp will contact Matija to get a test file. Existing masks can be fixed by @Mergpijp manually as long as he is the owner of the problem file.
* The uploaded files have different owners, caused by who ran the application process during uploading. If it was uwsgi/Emperor, the owner is wapglobort, which is highly inconvenient in combination with the previous problem because then we cannot change the mask. This will not happen in the future anymore because we will make sure @Mergpijp runs the process until we understand the problem better. For all existing files, C&CZ will set @Mergpijp as owner .

**Comment by Woseseltops** [comment]
@Mergpijp couldn't reproduce the problem with the file of Matija, but will try again on the production environment.

**Comment by Mergpijp** [comment]
I do not remember the issue with the file of Matija but I can now get a error if file is not uploaded I only need the file.

**Comment by Woseseltops** [comment]
Will reopen if we encounter this again.
