### ISSUE TITLE
Enable 'drag and drop' uploading

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#53]
For example like this (but you can pick another solution): https://www.smashingmagazine.com/2018/01/drag-drop-file-uploader-vanilla-js/

![uploader-preview](https://user-images.githubusercontent.com/1909317/86451841-c1b73f00-bd1b-11ea-8267-8191eb15e5b0.gif)

**Comment by Mergpijp** [comment]
This is done using dropzonejs took some time.

**Comment by Woseseltops** [comment]
Tried it, it works.
