### ISSUE TITLE
Add extendable category system for files

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#54]
Right now, you can upload multiple files, and select 1 cover file for a publication. We want to revise this system to work like this:

* Each uploaded file is listed below each other, or shown if it's an image, and has its own box where to pick a FileCategory.

* This category system works like many other category systems in the web application in that users should be able to add a new category if not available (like with 'Language').

* We can already add the FileCategories 'Front cover', 'Back cover', 'Frontispiece', 'Title page', 'Copyright page', 'Dedication', 'Table of contents', 'Preface', 'Bibliography/Index', 'Illustration' and 'PDF'. 

* I don't think it's needed that you can select files uploaded for other publications, like you currently can.

**Comment by Woseseltops** [comment]
As discussed today, we think this issue set get higher priority

**Comment by Mergpijp** [comment]
Finished this issue; cannot access foreign key from FileCategory form so that is a bummer any idea how I can?
Furthermore I do not understand this point: 

I don't think it's needed that you can select files uploaded for other publications, like you currently can.

@Woseseltops

**Comment by Woseseltops** [comment]
It seems to be working, we'll reopen if we want to extend this sytem.
