### ISSUE TITLE
Detail view: list/show files and images

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#55]
List and (if an image) display all uploaded files in the detail view, preferably somewhere near the bottom of the page. If a FileCategory is present (see #54 ), sort them according to the category in this order: 'Front cover', 'Back cover', 'Frontispiece', 'Title page', 'Copyright page', 'Dedication', 'Table of contents', 'Preface', 'Bibliography/Index', 'Illustration' and 'PDF'.

Perhaps it's better / more convenient in the future to make this system dynamic... maybe something like a field like 'order_index' can be added to FileCategory, where end users can put in a number that indicates where in the list of files this category should appear. For example, 'Front Cover' could get a 1, 'Back cover' a 2, so it the system knows that front covers should be shown first.

**Comment by Mergpijp** [comment]
@Woseseltops I have trouble saving related field 'Publications' at UploadedFile edit or create. 
It works now but I don't know why. Ive set ordering to order_index but it is not working in the detail view.

**Comment by Mergpijp** [comment]
Hmm. Think I found a bug in my code. I simplified adding/ removing publications by just clear out the existing list and add everything that is currently in the select2 container.

**Comment by Mergpijp** [comment]
I have made the dynamic version and added Meta class to the models.py. I had it in forms.py which was not working. Now it works.

**Comment by Woseseltops** [comment]
Great, thanks @Mergpijp . Is it deployed already? Because in the current detail view I see a list of uploaded files and an (of course empty) column for file category, but not this yet:

> (if an image) **display** all uploaded files

**Comment by Mergpijp** [comment]
Yes was not deployed yet. But is now

**Comment by Woseseltops** [comment]
To do: if an image, show (small) image

**Comment by Mergpijp** [comment]
Yes this is done was easy deploy later.
