### ISSUE TITLE
Searching files/images

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#56]
Add an option to the search system where you can select that you only want publications that have files/images with a particular FileCategory (see #54); for example only publications for which a front cover is present.

**Comment by Mergpijp** [comment]
This seems already done or am I missing something? Will deploy soon.

**Comment by Mergpijp** [comment]
I do not really get it; this is the same as making filecategory a searchable field?

**Comment by Woseseltops** [comment]
Turns out I am the one who was confused about this, it's working!
