### ISSUE TITLE
Describing content in images

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#57]
Step 1
====
For each uploaded file, you can already select 1 FileCategory (see #54). In this issue we want to add another field to uploaded files, where you can select one or more ImageContent. Like everywhere on the website, this system should be extendable. 

An example usecase:
* The user has uploaded a file.
* Sets it FileCategory to 'Front cover'.
* Realizes that Jesus is on the front cover, so adds this as ImageContent.
* Realizes that Mary is on the front cover, so wants to add this as ImageContent.
* Sees 'Mary' is not available as ImageContent so adds it on the fly.

Step 2
====
The option to search for all publication that have an uploaded file with a particular ImageContent, like searching for all publication with a picture of Mary in them.

**Comment by Woseseltops** [comment]
A possible step 3 could be that you search for publications that have an uploaded file with a particular ImageContent AND a particular FileCategory (for example: all publications with Mary on the front cover), but let's ask that to the users after this is implented.

**Comment by Mergpijp** [comment]
Okay, had some trouble with dropzonejs also I tried the TagWidget but it gave some errors I don't know if it is desired though.
This issue is complete.

**Comment by Woseseltops** [comment]
Great, these are not deployed yet, are they? I will close this issue once I've verified it works :)

**Comment by Woseseltops** [comment]
Saw it working!
