### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#58]
Dear Emmanuel,
Hope you are well. Just sent an email. We just had a team meeting for the ERC project and the team is wondering about any updates in the database and the cover photo issue that you guys discussed with Prof. Heleen.

Could you get back to me on that?

Thanks,

Elise

**Comment by Woseseltops** [comment]
Hi @Elisagig , for completeness: as far as I'm aware Emmanuel made quite some progress over the last few weeks, you can read about it in the various issues he is working on; for example, the thing we discussed with Heleen is issue #54 .

**Comment by Mergpijp** [comment]
Hi @Elisagig, just like Wessel says. Wessel added some extra issues for me to work through. Now I am however out of issues. I will be working on a second project.

**Comment by Elisagig** [comment]
Dear @Mergpijp thanks a lot for you and @Woseseltops. They were wondering particularly about the Cover photo thing. Will look at issues. Thanks

**Comment by Elisagig** [comment]
Dear @Mergpijp thanks a lot for all the work so far on the database. Good luck with the second project and many many regards
