### ISSUE TITLE
Make cover image in the list view go to the detail page (same as 'view' link)

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#59]

**Comment by Mergpijp** [comment]
Furthermore I would like to make it so that if a user is typing a hyperlink it will display as a link, any ideas how to implement that?

**Comment by Woseseltops** [comment]
Maybe find all urls with a regex like `/https?://[\w[.!?\\/-]+/` and put `<a href="` before it and `">link</a>` after it?

**Comment by Mergpijp** [comment]
Then I need to parse the page and run a regex on it . I do not think that is possible with django.

**Comment by Woseseltops** [comment]
Now that we are discussing this issue, we don't understand anymore what we were talking about.
