### ISSUE TITLE
When navigating, return only what was selected (instead of general search)

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#60]
For example, right now when selecting the FileCategory 'preface', it does a general search for 'preface', while we want to only have publications with an UploadedFile with FileCategory 'preface'.

**Comment by Mergpijp** [comment]
The problem is for related fieds like imagecontent and filecategory they are linked to uploadedfiles, but I can not search the ids.

**Comment by Mergpijp** [comment]
The question remains if this is desired for image_title it now does a general search.

**Comment by Mergpijp** [comment]
Image_title does a exact search do not know what they want.
