### ISSUE TITLE
Automatic cover image selection for the list view

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#61]
Right now we have two systems:

* System 1, where for each publication you have to manually select which uploaded file will function as the cover image. This is then what is shown in the list view of publications.
* System 2, where you can select a file category for each uploaded file, and 'cover image' is one of the categories. 

System 1 can be removed, and system 2 should be used for the list view. Start with a an uploaded file with file category 'cover image'; if there is no cover image it could show the frontispiece, and if that is not available the title page, and if that's not available just an illustration.

**Comment by Mergpijp** [comment]
I find this altering from cover image questionable what if the user does not want a cover image but did add the other images?

**Comment by Woseseltops** [comment]
Is good to think about @Mergpijp . I expect that it is unlikely that users do not want a cover image... but we could add this as an option in case users complain?

**Comment by Mergpijp** [comment]
Okay implementend this and did so by making a variable in the context (that gets passed to the front end). Because each publication has one or zero cover images I filled the cover_images with None if non available. I zipped the variable publications and cover_images so that I can loop over them simultaneously. Users need to set filecategory if they want the image to be displayed as cover image.

**Comment by Woseseltops** [comment]
Hey @Mergpijp , as reported by @Elisagig, I think it's not working yet: if I go to the list of publications, there are no images, while there are publications that have uploaded images with the file category set. My best guess is that this because you hardcoded the names of the categories as I listed them above, but on the live server the names are actually different. Also, with this being hardcoded, the system will break every time user changes a name of a category. 

Suggestion for improvement: add a 'list_view_priority' integer field to FileCategory that can be set in the admin. When selecting the best image for the list view, the system could then sort all associated files by their list_view_priority, and pick the first one. These could be the priorities of the file categories currently specified:
* Front cover: 1
* Frontispiece: 2
* Title page: 3
* Illustration: 4
* All others: 5

This way, if users decide that title pages are not so good to show in the list view after all, this can quickly be changed in the admin without changing the code. This system also means that there always is some kind of image, as long as the file category is set... and perhaps we can even make it so that if there are uploaded files, but they don't have the file categories, it just picks the one that was first uploaded?

**Comment by Mergpijp** [comment]
I just changed the algorithm somewhat. It was hardcoded yes and now there is a integer list_view_priority. The hard part is the last bit were you have to pick the first file that is uploaded. It is done but I need to check if the file is really a image. How to do that?

**Comment by Woseseltops** [comment]
You could start with just checking the extension? Various things can go wrong there, but I guess it would work 99% of the time as the users expect?

**Comment by Mergpijp** [comment]
I used pillow and tried to open image in python if it gives an exception I continue iterating the uploaded file list.
Did not test thoroughly yet but it seems to be working; there are some images in the listview.

**Comment by Woseseltops** [comment]
Looks like this is working and I got no complaints during the meeting today. Let's reopen if any problems are discovered here.

**Comment by Elisagig** [comment]
Yes. I actually did not ask if people have this problem still but nobody complained and it also looked ok for me
