### ISSUE TITLE
Column font decreased and images disappeared

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#63]
Hi,
My colleague has reported that while uploading images, the "column for the cover-images has decreased a lot and the images have disappeared". He reported this yesterday. Might be a glitch. Kindly check. Thanks

**Comment by Mergpijp** [comment]
It is not a bug it is a feature. Now the cover image is set by setting the filecategory of a uploadedfile. See https://github.com/Mergpijp/GlobalOrthodoxy/issues/61 for details and priority settings.
