### ISSUE TITLE
Crop images in the list view

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#66]
Right now, images are stretched to make them uniform in the list view, but the users prefer the top and bottom to be cut off so you only see the center part. This can be done with some CSS magic if I'm not mistaken.

This means:
* The 'higher/longer' an image is, the more 'zoomed in' an image will appear in the list view, and the more pixels are not visible.
* If an image is in landscape mode, wider than it is high, the left and right side need to be cut off.

**Comment by Mergpijp** [comment]
Following your story I have found the following [link](https://www.digitalocean.com/community/tutorials/css-cropping-images-object-fit ). 
I use object-fit:cover. This seems right? Keeping the aspect ratio and cut of the left and right. (when in landscape mode).

**Comment by Woseseltops** [comment]
Exactly, object-fit:cover seems to be what they want

**Comment by Woseseltops** [comment]
Saw it working!

**Comment by Elisagig** [comment]
Prima
