### ISSUE TITLE
Prefill the publication field in the popups

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#67]
In various popups around the application, most notably when uploading files, there is a field to specify the publication the thing you are creating belongs to. This field should be prefilled if the user is already working on a publication (like during creation of a new publication). For example, when I am creating a new publication 'xyz' and I upload a file, the 'publication' field in the file upload popup should already be set to 'xyz'.

Technical suggestion: maybe you communicate the publication to be linked via GET argument in the URL?

**Comment by Mergpijp** [comment]
This is hard to make, because the publication you are currently working on does not exist yet. One first has to save the publication.

**Comment by Woseseltops** [comment]
Challenge accepted B)

How about creating a publication object under the hood as soon as the users starts creating a new publication, so we have something to refer to? Perhaps you can add an extra boolean field 'stub' that is true for publications that have never been saved yet (and thus have all their fields empty), and is set to false as soon as the user clicks 'save' the first time?

When opening a popup, you could pass along the id of this newly created stub, so you can prefill the publication field? Of course, you cannot fill any information on this newly created publication yet, like you do for existing publications...

![image](https://user-images.githubusercontent.com/1909317/94922307-44d26780-04ba-11eb-8c14-27c0452f76e2.png)

... so perhaps you can just make it say *new publication* there?

**Comment by Elisagig** [comment]
Thanks for following up. Good to know. Please let me know if you have further questions

**Comment by Mergpijp** [comment]
Since I deleted the publication field in popups all together this issue is redundant now.

**Comment by Woseseltops** [comment]
@Mergpijp explained that the publication field wasn't really necessary, even for UploadedFiles.
