### ISSUE TITLE
Language or Languages

### ISSUE THREAD

**Issue by Mergpijp** [Mergpijp/GlobalOrthodoxy#7]
What are your preferences for the Language field should it be multiple languages per publication or should we restrict it to one language per publication?

**Comment by Elisagig** [comment]
1. Do you mean the translation language or the gewone language field

Discussed the issue with my colleagues and we thought to make it multiple languages because we have books in more than one language.

Thanks

**Comment by Mergpijp** [comment]
Yes, the language field. Currently accepts multiple languages. So this is ok, closing issue.
