### ISSUE TITLE
The image content field should work similar to the keyword field

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#71]
So you don't have to click the 'plus icon' all the time while describing an image. Related to #70 .

**Comment by Mergpijp** [comment]
Yes I get that you mean the imagecontents variable at uploadedfile?

**Comment by Woseseltops** [comment]
Yes sorry that is what I meant

**Comment by Woseseltops** [comment]
This works, maybe you can rename the label from 'keywords' to 'keys (use semicolon to separate)'?

**Comment by Woseseltops** [comment]
@Elisagig also mentioned this in #91 , so let's continue this issue there.
