### ISSUE TITLE
Split the title list into 2 separate list views

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#73]
The first one should have the function of a generic overview of what's in the database, and should have the fields cover image, original title, translated title, author, publication date, publication place (shown as city, country), the language and the genre. This list view should be accessible from a new 'overview' button in the top bar. 

The second is the 'real' publication list view, and should only contain the cover image, the title, the translation, the author and the publication date.

**Comment by Mergpijp** [comment]
You write 'tha author' but there could be many authors on a publication. How to solve this? Same goes for translation

**Comment by Woseseltops** [comment]
Would listing them all, separated with commas, work?

**Comment by Mergpijp** [comment]
Yes it works but somehow it doubles the publication I tried to use distinct() in the backend but i get:  Cannot create distinct fields once a slice has been taken. really weird.

**Comment by Woseseltops** [comment]
> but i get: Cannot create distinct fields once a slice has been taken. 

I guess this was solved, right? It looks like it's working!

**Comment by Elisagig** [comment]
Yep I guess so
