### ISSUE TITLE
Figure out what is the problem why Heleen cannot upload two files and fix it.

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#74]
Heleen emailed them to us

**Comment by Mergpijp** [comment]
I tried uploading both files test and test2 as description to the database and it worked. Really peculiar that Heleen did not get this to work. Note this is without updates to the webapplication!

**Comment by Woseseltops** [comment]
Okay, so we are not able to reproduce this issue so far. 

Heleen also mentioned that it was not just these two files; it occurs more often. This is in agreement with the fact that Habtom also seems to have this problem for some files.

**Comment by Elisagig** [comment]
Solved
