### ISSUE TITLE
Add sort buttons for all columns in all list views

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#75]
They are already there in the title list view, they should be in all list views.

**Comment by Mergpijp** [comment]
This is done

**Comment by Mergpijp** [comment]
This is done with the exception of dates because they are entered as character there is no way of sorting that.

**Comment by Woseseltops** [comment]
Let's discuss the dates during the meeting in a few minutes.

**Comment by Woseseltops** [comment]
There is a separate issue for the dates now!
