### ISSUE TITLE
Add filter fields for the list view

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#76]
Like this https://datatables.net/extensions/fixedheader/examples/options/columnFiltering.html

Might be technically hard because we use pagination at the moment.

**Comment by Woseseltops** [comment]
Note: this issue is not approved by the users yet.

**Comment by Mergpijp** [comment]
Any update on this? I am running out of issues.

**Comment by Woseseltops** [comment]
We're doing this another way.
