### ISSUE TITLE
Error loading last page of database

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#77]
My colleague Mattija uploaded a publication on Friday and he does not know if it got saved and when he tries to see it in the overview he gets this error (see photo).
![database_error](https://user-images.githubusercontent.com/61408472/92454711-17e3ab00-f1c1-11ea-9bb7-dbe3eae23bdf.png)

**Comment by Mergpijp** [comment]
There is a bug in the fileselector when there are no files it picks the oldest one. Apparantly there are files without a file uploaded.
This has been fixed will be deployed later.
