### ISSUE TITLE
Save progress, undo delete or go back to previous state

### ISSUE THREAD

**Issue by Mergpijp** [Mergpijp/GlobalOrthodoxy#8]
This is issue is generated after contacting Habtom.
He specifically emailed me for a functionality of a thrash bin. So if a publication is deleted it will appear in a bin and you can restore it. For clarification there are three options:

1) While making or editing a publication save the progress. So a user can close the webpage and come back to a previously edited or to be added publication.

2) Make a thrash bin for deleted publications. A publication could have a field 'is_deleted' and then not appear in the main list. One can restore the publication by going to the thrash bin and press restore, it will then appear in the main publication list.

3) This is what I have found so far. Storing states after update/delete/create and return to a previous state when desired. This will have the same effect as 2) but is a little bit harder and requires knowledge of the users. 

So @Elisagig what will be your preference?

**Comment by Elisagig** [comment]
Sorry did not reply yesterday because I am free on Wednesdays and Thursdays. Option 2 is good. Thanks a lot

**Comment by Elisagig** [comment]
See my new comments

**Comment by Mergpijp** [comment]
This is done.
