### ISSUE TITLE
Cover images: can't see whole cover anymore. 

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#80]
Format of the front cover images on the main page are more zoomed in so we can't see whole cover. Parts of the titles are missing.

**Comment by Mergpijp** [comment]
Dear Elise,

I thought this was what was meant. I discussed this with Wessel earlier. Please go to this [website](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)
Cover is what is currently set. What do you want?

**Comment by Elisagig** [comment]
Ok. I will discuss with team. They mentioned that not the whole image is appearing compared to the past. Will let you know. I talk to them on Friday. Thanks Emmanuel

**Comment by Elisagig** [comment]
Heleen suggested we choose the second option object fit: contain @Mergpijp

**Comment by Woseseltops** [comment]
Related to #66 . I will reopen this because the team has not decided what they want exactly.
