### ISSUE TITLE
Can't edit for old entries that have photos

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#81]
We are going through a strange thing: whenever we want to edit a previously entered data it doesn't work anymore. We discovered that entries that have no photos can be edited, but entries that have photos cannot be edited. Kindly check @Mergpijp

**Comment by Mergpijp** [comment]
Dear Elise,

What do you mean by edit? I cant edit the image title the filecategory and image content.
Seems to be working. I will try editing the picture next.

**Comment by Mergpijp** [comment]
Maybe cannot see that a photo is uploaded once you edit one. The photo is uploaded and re-uploading edits the photo or file.

**Comment by Elisagig** [comment]
No I do not mean editing the photo itself. I mean that whenever you go in and want to add something about that book, it does not work if it has a photo. For example:
- Heleen uploads a book. She adds all the information. She adds a photo. One hour later she wants to change the name of the author. She gets a weird page saying it is not possible.  
- Elise uploads a book but she does not add a photo. One day or one hour later she wants to change the name of the author. It works. (Because there is no photo)

**Comment by Elisagig** [comment]
Ok now I see this is solved now. We do not have this problem anymore
