### ISSUE TITLE
Overview has more items than needed

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#83]
In the "overview" we suddenly have more columns (content) than what was previously requested by Heleen. We will discuss that today.

**Comment by Woseseltops** [comment]
Related to #73

**Comment by Mergpijp** [comment]
I cant remember adding more? I just did what was told by Wessel. Like to hear more.

**Comment by Woseseltops** [comment]
Hmm, something went wrong somewhere, but it doesn't matter... let's fix it. The latest wishes that Heleen sent us, for all publication lists (both the general overview, and for things like search results):
* Cover image
* Title original
* Title translation
* Author name
* Publication date
* Publication place
* Actions

Furthermore, Heleen suggests to remove the cover image and action columns in all places other than the general overview, but I'm going to ask a question about this :).

**Comment by Woseseltops** [comment]
Heleen replied (quite some time ago already)... please make the all publication lists the same again. So both the general overview in the search results should have the columns:
* Cover image
* Title original
* Title translation
* Author name
* Publication date
* Publication place
* Actions

**Comment by Elisagig** [comment]
The team is complaining that this problem is still there. They are also mentioning that still there are two overviews. 

"We have two overviews still: one when we click on the logo of the university, and the general overview. The table of contents also includes items we did not add"

**Comment by Woseseltops** [comment]
Correct @Elisagig , Emmanuel did not work on this issue since my last message (otherwise you see little messages here saying that he 'pushed a commit'). Let us know if this issue should get higher priority.

**Comment by Elisagig** [comment]
Yes could you do it? I would say that in terms of priority it is not high but the team asked me a couple of times about it. Thanks

**Comment by Woseseltops** [comment]
Okay I'll Give this the high prio tag once the other issue is done.

**Comment by Woseseltops** [comment]
We now have to seperate html tables, we decided to make it one.
