### ISSUE TITLE
"Search": Field Error 

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#84]
When I click something under "Search" I get something saying "Field Error" and a strange [page]
![image](https://user-images.githubusercontent.com/61408472/94896025-dfb44d00-048c-11eb-9599-1bc1bba4f8c6.png)

**Comment by Woseseltops** [comment]
I also get it if I list the UploadedFiles, and then click one (which, if I understand things correctly), is the same thing as searching under the hood.

**Comment by Mergpijp** [comment]
Yes these were outdated search fields should be solved now.

**Comment by Woseseltops** [comment]
Looks solved, so I close this. We'll reopen if this pops up again.

**Comment by Elisagig** [comment]
Done
