### ISSUE TITLE
Replace 'publication date' string field with 'publication year' integer field

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#86]
Step 1. Add the *publication year* integer field
Step 2. Make an overview of publications which have something else than a year in the *publication date* field, copypaste it to this issue, and then manually clean it so it only contains the year
Step 3. For all existing publications, fill the *publication year* with the (now clean) *publication date*
Step 4. Remove the *publication date* field.
Step 5. Make the publication year field sortable.

**Comment by Mergpijp** [comment]
step2:
6: november 1996 6: 1996
8: 2019 (2012 Ge'ez) 8: 2019
10: June 2009 10: 2009
19: 2009/1982 19:2009
31: dec. 2019: 31:2019

**Comment by Woseseltops** [comment]
It works, great.
