### ISSUE TITLE
List deployments to live server somewhere

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#87]
The team indicates they want more insight in what @Mergpijp builds when. This way, when they encounter a problem, they can have an idea how long they problem might have been there already (and not worry if it was introduced only 5 minutes ago... in that case @Mergpijp might still be working on it). 

To solve this, there should be a list somewhere, for example somewhere in the application (small button called 'releases'?). Update that list each time you deploy to the live server, along with links to the issues you work on. Something like:

* Oct 2, 1300h: #x #y
* Oct 3: 1330h: #z

This could be a text page that you manually update, but you could also automate this if you like, by adding a Django model 'Release' with fields like date and issues_worked_on. A script could then do the git pull AND create a new release object automatically.

**Comment by Mergpijp** [comment]
So I wrote a parsing script and piped git log to the script. I got some nice overview now.
How can I automate this on the server right?
In the script I now use:
#!c:/Users/Emmanuel/Anaconda3/python.exe
To tell it were python is located I need to change that on the server right?
How do I create the django object in the script? My script is attached.

[gitLogParser.zip](https://github.com/Mergpijp/GlobalOrthodoxy/files/5365578/gitLogParser.zip)

**Comment by Woseseltops** [comment]
Before we go into the technical details of running such a script automatically... does this show commits or deployments? Because the latter thing is what mainly interests the users.

**Comment by Mergpijp** [comment]
Hmm yes i misread the post. But releases should have commits in them right? I think commit messages are helpful because they say what was done.

**Comment by Woseseltops** [comment]
> But releases should have commits in them right? I think commit messages are helpful because they say what was done.

Yes, as you can see in the example in my first message :)

**Comment by Woseseltops** [comment]
Current status: showing commits. Suggested improvement: get only the issue number from the commit message, and make it a link. The commit message itself can also be shown, but make it small.

**Comment by Mergpijp** [comment]
Yes you will not see any commit because gitlog is a standalone package. The font size failed but it looks good anyway.
