### ISSUE TITLE
search arabic with latin text

### ISSUE THREAD

**Issue by Mergpijp** [Mergpijp/GlobalOrthodoxy#9]
So Matija once told that mazamir results in مزامير and that salawat results in صلوات. However google translate for the latter gives: salavat (Persian detected). So consequently the search does not work. But for mazamir it is working. Do I need to support Persian as well? Now we use google translate only for Arabic. But as Matija mentioned: 'I guess something like this will also have to be done for Tigrinya/Amharic and Syriac at one point.'
What is your take on this?

**Comment by Elisagig** [comment]
Yes Persian is not important I think. Tigrinya/Amharic and Syriac I think, in addition to the existing Arabic. Though Syriac is a rarely used language, except for a small community. Arabic, Tigrinya and Amharic are more of a priority at this stage. Google mis-translation is possible always I guess.

**Comment by Woseseltops** [comment]
@Mergpijp says this is working. When more languages need to be supported, let us know.
