### ISSUE TITLE
Show UploadedFiles: replace the select2 field with a table and a search box

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#90]
Check the email I sent with We Transfer files. We noticed that when we search in the list we are editing for uploaded files or publications, the search function is not working. There is a big list and we need to scroll and look. More info in one of the Zoom videos I just sent. Thanks

**Comment by Woseseltops** [comment]
For clarity, this is not about the functionality inside the 'add new uploaded file' popup (as discussed in #67); this is about linking an uploaded file from a publication in the main window. In some cases this process goes wrong (see #62 for a bug related to this mechanism), but let's use this issue to talk about how things should work even if all goes okay.

What we currently have:

![image](https://user-images.githubusercontent.com/1909317/96995040-d8351080-152d-11eb-815c-d7bb266d1112.png)

Quick drawing of suggested solution:

![image](https://user-images.githubusercontent.com/1909317/96995634-c99b2900-152e-11eb-829f-90e3f7e08dc8.png)

Main differences are (1) all images are displayed in a table like structure and (2) working search functionality, where the image is added immediately (Javascript) as you click the search result.

**Comment by Mergpijp** [comment]
Any idea how to start? Is this just an advanced select2?

**Comment by Woseseltops** [comment]
No @Mergpijp what I'm suggesting is abandoning select2 altogether for uploaded files and building something custom instead. Just use basic Django functionality; iterate over the uploaded files within in the template, something like that.

By the way @Elisagig , what do you think of my suggestion?

**Comment by Elisagig** [comment]
Looks good for me. Just came out of a meeting with the team on the database. Will also ask their opinion

**Comment by Elisagig** [comment]
Could you please explain more about this? the team keeps complaining about the difficulty of searching for things in the database

**Comment by Woseseltops** [comment]
Of course, but what do you want to know? Perhaps we could discuss this next week @Elisagig ?

**Comment by Elisagig** [comment]
Yes thanks

**Comment by Woseseltops** [comment]
To get the search functionality working:
* Create a view search_uploaded_files with as argument a string, which returns a list of all uploaded files where the name matches the string somehow. In case of more than 10 results, limit to 10 results.
* Every time the users types something in the search box, do an ajax request to this view, and show the results under the search box with a button 'link' .
* Create a view link_uploaded_file with two parameters: the pk of the uploaded file and the pk of the publication. It returns an updated version of the table of uploaded files.
* If this 'link' button is clicked, empty the search box, remove the search results, and do an ajax request to the link_uploaded_file view. Use the response to update the table of uploaded files.
