### ISSUE TITLE
Price: currency field

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#92]
The field for price doesn't allow us to insert a currency symbol or not even a whole word. So for 3 euros, it is only possible to write '3e' like this. We are using different currencies. So any ideas how to do this? Thanks

**Comment by Woseseltops** [comment]
The price field currently is a numeric field (e is for scientific notation of numbers). @Elisagig and Matija decided they do not want it to be a freeform text field, so instead we want a *new separate currency field*. Unlike other fields (like church, language, etc), there is no need for the users to extend the options (so no foreign key to a separate model). Instead, it should be a fixed list with as options:

* USD: United States Dollar
* CAD: Canadian Dollar
* AUD: Australian Dollar
* EUR: Euro
* GBP: Pound sterling
* SEK: Swedish krona
* EGP: Egyptian pound
* LBP: Libanese pound
* ETB: Ethopian birr
* ERN: Eritrean nakfa
* ILS: Israeli shekel
* AMD: Armenian dram

**Comment by Elisagig** [comment]
Prima. thanks

**Comment by Mergpijp** [comment]
yes this was easy to make will be deploying later.
