### ISSUE TITLE
Trim titles in the list view

### ISSUE THREAD

**Issue by Woseseltops** [Mergpijp/GlobalOrthodoxy#93]
To prevent really high/long rows, let's only display the first x characters (up to you how much @Mergpijp ) and then ...

![image](https://user-images.githubusercontent.com/1909317/96996521-4aa6f000-1530-11eb-94fa-9c4b1e4421fe.png)

**Comment by Mergpijp** [comment]
I have looked for solutions on the web. I could not find anything better then [this:](https://stackoverflow.com/questions/3922739/limit-text-length-to-n-lines-using-css )
It looks kinda buggy with boxes around the text. Any ideas?

**Comment by Woseseltops** [comment]
How about doing it in Django/Python already, like adding a function to the publication model 'get_truncated_title' ? Inside that function, it's just a matter of limiting string length (and adding three dots), nothing more.

**Comment by Mergpijp** [comment]
Thanks never knew this was so easy.

**Comment by Woseseltops** [comment]
This is not live yet, is it?

**Comment by Woseseltops** [comment]
Based on remarks by Habtom, we want to do this for all columns.

**Comment by Mergpijp** [comment]
Did it for all titles is that sufficient?

**Comment by Woseseltops** [comment]
For completeness: @Mergpijp worked on this but not deployed yet.
