### ISSUE TITLE
uploading new files: one step? 

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#94]
Uploading new files – Current method (2 steps: 1. adding a new file in a pop-up window, and 2. adding it from an existing list of publications) is time consuming and often doesn’t work.
-Is there a possibility to create a one-step method of uploading images? E.g. to add a file via a new window, where we fill in all the information, and by clicking on ‘submit’ that it adds and saves images automatically (so without having to choose it from the list)?
-If not, we should at least be able to search for a publication in the ‘uploaded files’ list., since it is getting longer and longer, without having to scroll all the way down and finding it manually. (Search fields in all places in the database should work properly in any case)

**Comment by Mergpijp** [comment]
Yes the publications field is deleted not yet deployed. In other issues we are working on a new method for adding files to a publication. It is more graphical I am currently stuck and I am going to the university to ask for help.

**Comment by Elisagig** [comment]
Thanks. Succes

**Comment by Elisagig** [comment]
Message from my colleague Habtom 
"This happens when I go to Uploaded Files (From Navigate) and find my file in this long list (I can't do search for if I do that, I get the same Attribute error)... and then I click on the image title.
Now I am trying to go to either Edit/Dete... I went to Edit, and uploaded the JPG to replace the pdf-image but to no avail. If I go then to Titels, then I see the size is changed but no image ....(See below)
If I take the option of delete, then the whole file including the texts are [deleted".](url
![Habtomdownload](https://user-images.githubusercontent.com/61408472/102056519-ca449300-3dec-11eb-84b2-b5f7cde91b3b.png)
)

**Comment by Woseseltops** [comment]
Hi @Elisagig , do I understand correctly that Habtom is having problems with replacing the actual file for an UploadedFile entity? If so, I think this is a separate problem from what you describe in the first message of this issue (which sounds like #62 and #90 ). Perhaps we can use this issue for Habtom's problem only, and rename this issue to 'Replacing files in UploadedFile entity does not work'?

**Comment by Mergpijp** [comment]
Okay thanks for clearing up @Woseseltops will try to replace files see if that works.

**Comment by Mergpijp** [comment]
Okay I have been seeing peculiar events. So when editing a uploadedfile it did not recognize the url: uploadedfile/proces/1/. I removed the trailing slash (/)  and it worked I can edit files! Will be deployed later.
