### ISSUE TITLE
Edit option not working well 

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#95]
The "edit" option to add new image or work on it and then choose "file"/upload file it is still not working. When you go to "view" you can't find it. We have to go to uploaded files and do it again. This takes time. this is not the case for all files. The option to connect images to publication is difficult to find. There should be an easier way to link it. We want to know:
a. What the problem is and why it does not always work
b.If we can do it all in one step to save time (edited)

**Comment by Mergpijp** [comment]
Will need to look into the not working part. Maybe a detailed reconstruction of steps will help me detect the issue.

**Comment by Elisagig** [comment]
Thanks. Succes

**Comment by Elisagig** [comment]
Maybe we do it on Friday the 27th (not this Friday the following one). Are you free at 10:00?
