### ISSUE TITLE
Uploading images and Linking images to publications

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#96]
Message from Heleen: 
"As to the uploading of images: when adding a random image in a different category from Front Cover, it was added as Front Cover image in the overview (in a case where there was no Front Cover image)".

Message from my colleague Matija:
"Regarding Linking an image to the right publication - if you are on the 'Create page', uploading a new publication and you are adding a new file (image), you cannot link it to the current publication that you are working on - it is not on the list since it has not been saved yet. We don't want to go the other way around and link the image through navigate --> uploaded files --> edit and then link it to the desired publication (also, at least search option would be helpful here since the list is getting pretty long). That is time consuming and sometimes it doesn't even work, as some of us experienced it. So it would be good if while being on the Create page - uploading a new publication and then a file, that it links automatically on the spot (that is another thing that worked only occasionally, as we could see during the meeting as well)".

**Comment by Mergpijp** [comment]
1) yes the system picks a image as front cover if none is selected.
2) This problem is already in other issues and I am working on a system to link uploaded files more easily to the publication. I hope it can be a easy solution for new publications/

**Comment by Woseseltops** [comment]
> "As to the uploading of images: when adding a random image in a different category from Front Cover, it was added as Front Cover image in the overview (in a case where there was no Front Cover image)".

Indeed the behavior as described here: #61 . If you want things to work differently, please reopen that issue and describe the desired functionality :) . 

> Regarding Linking an image to the right publication

What Matija is describing sounds pretty much like what we are working on in #62 , which is still work in progress!

If you agree that these existing issues are indeed about the same topics, @Elisagig , could you please close this one? Thanks!
