### ISSUE TITLE
Newest seen first in the overview

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#97]
It saves time to see the new things on top in the overview  after we add them instead of going next next, based on the date we added them in

**Comment by Woseseltops** [comment]
Proposed steps:
1. Add 'date_created' as field to the model
2. Add date created as column to the overview, and make it sortable
3. Make it default sorting (if the previous steps are not enough already)

**Comment by Mergpijp** [comment]
Yes thanks for the steps @Woseseltops. This is done will be deployed later.

**Comment by Elisagig** [comment]
Hi guys this is still annoying my colleagues. They want the first to be seen in the beginning instead of doing "next" to page 5 for example. Thanks

**Comment by Woseseltops** [comment]
This seems to be working, what is it you are still missing @Elisagig ?

**Comment by Elisagig** [comment]
I don't know why they asked again. Will check and inform
