### ISSUE TITLE
Too narrow column for title

### ISSUE THREAD

**Issue by Elisagig** [Mergpijp/GlobalOrthodoxy#99]
The title text in the column is too narrow in the layout page. We want a wider layout for the title of the book. 
![image](https://user-images.githubusercontent.com/61408472/102332370-46c1a800-3f8c-11eb-8d83-0c51bafee082.png)

**Comment by Woseseltops** [comment]
Hey @Elisagig , this is issue #93 ! I'll close this one, let me know if you disagree :)
